os: osx
osx_image: xcode9.2
env:
  - COLUMNS=240
before_install:
  - brew cleanup
  - brew uninstall gdal mercurial postgis python
  - brew update
  - brew upgrade
  - brew cleanup
install:
  - brew install advancecomp jpeg-turbo
  - brew install https://raw.githubusercontent.com/lovell/homebrew-core/vips-new-github-org/Formula/vips.rb --without-fftw --without-graphicsmagick --without-poppler
script:
  - ./package.sh
addons:
  artifacts:
    s3_region: eu-west-1
