os: osx
osx_image: beta-xcode6.2
install:
  - brew update
  - brew install --build-from-source gdk-pixbuf --disable-gio-sniffing --without-libtiff --without-gdiplus --disable-modules --with-included-loaders=png,jpeg
  - brew install --build-from-source homebrew/science/vips --with-webp --without-fftw --without-poppler
script:
  - ./package.sh
addons:
  artifacts:
    s3_region: eu-west-1
