os: osx
osx_image: xcode9.2
env:
  - COLUMNS=240
install:
  - brew uninstall python
  - brew update
  - brew upgrade
  - brew install advancecomp
  - brew install vips --without-fftw --without-graphicsmagick --without-poppler
  - brew info vips
script:
  - ./package.sh
addons:
  artifacts:
    s3_region: eu-west-1
