os: osx
osx_image: beta-xcode6.2
install:
  - brew update
  - brew install homebrew/science/vips --with-webp --without-fftw --without-poppler
script:
  - ./package.sh
addons:
  artifacts:
    s3_region: eu-west-1
