os: osx
osx_image: xcode9.3
env:
  - COLUMNS=240
install:
  - brew update
  - brew install advancecomp
  - brew install vips --without-fftw --without-graphicsmagick --without-poppler
  - brew info vips
script:
  - ./package.sh
addons:
  artifacts:
    s3_region: eu-west-1
