os: osx
osx_image: xcode9.2
env:
  global:
    - COLUMNS=240
    - HOMEBREW_OPTFLAGS="-march=corei7"
before_install:
  - brew cleanup
  - brew uninstall boost carthage cgal dirmngr gdal gnupg go gpg-agent libassuan libgeotiff libgpg-error liblwgeom libspatialite maven mercurial pinentry postgis postgresql python sfcgal swiftlint
  - brew update
  - brew upgrade
  - brew cleanup
install:
  - brew install advancecomp
  - brew install https://raw.githubusercontent.com/lovell/homebrew-core/gdk-pixbuf-builtin-loaders/Formula/gdk-pixbuf.rb --builtin-loaders="png,jpeg"
  - brew install vips --without-fftw --without-graphicsmagick --without-poppler
script:
  - ./package.sh
addons:
  artifacts:
    s3_region: eu-west-1
