os: osx
osx_image: beta-xcode6.2
env:
  - COLUMNS=240
install:
  - brew update
  - brew install advancecomp
  - brew install gdk-pixbuf --without-modules --with-included-loaders="png,jpeg"
  - brew install homebrew/science/vips --with-webp --without-fftw --without-poppler
  - brew info gdk-pixbuf
  - brew info vips
script:
  - ./package.sh
addons:
  artifacts:
    s3_region: eu-west-1
