language: objective-c
before_install:
  - brew tap homebrew/science
  - brew update
  - brew install vips --with-webp --with-graphicsmagick
install:
  - mkdir include
  - for path in $(pkg-config --cflags --static vips | tr ' ' '\n' | grep '^-I' | cut -c 3- | sort | uniq); do cp -R ${path}/ include; done;
  - mkdir lib
  - for path in $(pkg-config --libs --static vips | tr ' ' '\n' | grep '^-L' | cut -c 3- | sort | uniq); do find ${path} -type f -name *.dylib | xargs -I {} cp {} lib; done;
  - version=$(pkg-config --modversion vips)
  - GZIP=-9 tar cfz build/libvips-${version}-darwin-x64.tar.gz include lib
script:
  - ls -al build
  - tar tf build/libvips-${version}-darwin-x64.tar.gz
deploy:
  provider: s3
  region: eu-west-1
  bucket: sharp-libvips
  skip_cleanup: true
  local_dir: build
  access_key_id: AKIAIMEKPFIYQLN5EKXQ
  secret_access_key:
    secure: QXJQMurH2DAJwbJZZLkZ4xKLnLPtg4pNicLMRjg/pyqFcQW9MvwApzbnk2tmYKNAsGRTBr2+GoCvkBN7hOAc/UimD9qVzb/PojyMvH0npnDZrk+3Gz5T73ZvsF8AeAVs1gW9D4qQTl+qlhkQbB7oebssn/dbBT6XIHVN2eC+dXJEWIyxSNCxzgVU7U708yQLH0evg8ZQjuHQ+4rbSaaXzT4iqdFt/Achjb/dVBpNzhynA9MmC35MBopEXUNtjGTRnGv3r7dP6De+MGJH3UNWgS6UyG5cFGqOOCLqrX8hg6JDHMYDQpbPpPlk2BsNX4hBJQmNd+4DPNwRkcaqkl4GgwdpSsBoBAQIBmCyCOvJ9Wpt6V0CP5fyLJyFSxV7jej58S61GprUarsXKIC+fUCY4zWkBqLl0VYhyChSlIIkkjfAZWwAhRAzqFme0mcfcGLGLOOrW9QqFCVo6o2tuS/TcgR3UFeNZXvdu5DRjkVdr4/VI6dl3B2A4kVQ/scHSsqoPcqyAen8yIBuWreSbpIsH7m64Eqh1wO7Fa+DImd7SjQhabY6b676kec214MydEwVuE99ADuRmwxI6FOYcyXLFm9bu70n6R+vRnLy0VlP9ZNdauU/x0tp9yQy/hp9LFKuL37mvOUjDf3xw4bXE3ZGMsgBhGZO4iPzCmOtukxsXYg=
