os: osx
osx_image: xcode9.2
env:
  global:
    - COLUMNS=240
before_install:
  - brew cleanup
  - brew uninstall boost carthage cgal dirmngr freexl gdal go libgeotiff liblwgeom libspatialite maven mercurial postgis postgresql python sfcgal swiftlint
  - brew update
  - brew upgrade
  - brew cleanup
install:
  - brew install advancecomp
  - brew tap lovell/package-libvips-darwin https://github.com/lovell/package-libvips-darwin.git
  - brew install lovell/package-libvips-darwin/gdk-pixbuf --build-bottle
  - brew postinstall lovell/package-libvips-darwin/gdk-pixbuf
  - brew install lovell/package-libvips-darwin/vips --build-bottle
script:
  - export PKG_CONFIG_PATH="${PKG_CONFIG_PATH}:/usr/local/opt/libffi/lib/pkgconfig"
  - ./package.sh
addons:
  artifacts:
    s3_region: eu-west-1
